const practice_info = {
    key_press: [
        {
            picture: "pictures/13_50_different.jpg",
            number: 13,
            expected: "different",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different',
						
        },
        {
            picture: "pictures/13_50_same.jpg",
            number: 13,
            expected: "same",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different',
        },
        {
            picture: "pictures/13_150_different.jpg",
            number: 13,
            expected: "different",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different',
        },
        {
            picture: "pictures/13_150_same.jpg",
            number: 13,
            expected: "same",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different',
        },
        {
            picture: "pictures/14_50_different.jpg",
            number: 14,
            expected: "same",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different',
        },
        {
            picture: "pictures/14_50_same.jpg",
            number: 14,
            expected: "different",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different',
        },
        {
            picture: "pictures/14_150_different.jpg",
            number: 14,
            expected: "same",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different',
        },
        {
            picture: "pictures/14_150_same.jpg",
            number: 14,
            expected: "different",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different',
			
        },
        {
            picture: "pictures/15_50_different.jpg",
            number: 15,
            expected: "same",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different',
			
        },
        {
            picture: "pictures/15_50_same.jpg",
            number: 15,
            expected: "different",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different',
			
        },
        {
            picture: "pictures/15_150_different.jpg",
            number: 15,
            expected: "same",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different',
			
        },
        {
            picture: "pictures/15_150_same.jpg",
            number: 15,
            expected: "different",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different',
			
        },
    ],
};

const main_info = {
    key_press: [
        {
            picture: "pictures/1_50_same.jpg",
            number: 1,
            expected: "same",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different', 

        },
        {
            picture: "pictures/1_50_different.jpg",
            number: 1,
            expected: "different",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different',

        },
        {
            picture: "pictures/1_150_same.jpg",
            number: 1,
            expected: "same",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different',
        },
        {
            picture: "pictures/1_150_different.jpg",
            number: 1,
            expected: "different",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different',
        },
        {
            picture: "pictures/2_50_same.jpg",
            number: 2,
            expected: "same",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different',
        },
        {
            picture: "pictures/2_50_different.jpg",
            number: 2,
            expected: "different",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different',
        },
        {
            picture: "pictures/2_150_same.jpg",
            number: 2,
            expected: "same",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different',
        },
        {
            picture: "pictures/2_150_different.jpg",
            number: 2,
            expected: "different",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different',
        },

        {
            picture: "pictures/3_50_same.jpg",
            number: 3,
            expected: "same",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different',
        },
        {
            picture: "pictures/3_50_different.jpg",
            number: 3,
            expected: "different",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different',
        },
        {
            picture: "pictures/3_150_same.jpg",
            number: 3,
            expected: "same",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different',
        },
        {
            picture: "pictures/3_150_different.jpg",
            number: 3,
            expected: "different",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different',
        },

        {
            picture: "pictures/4_50_same.jpg",
            number: 4,
            expected: "same",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different',
        },
        {
            picture: "pictures/4_50_different.jpg",
            number: 4,
            expected: "different",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different',
        },
        {
            picture: "pictures/4_150_same.jpg",
            number: 4,
            expected: "same",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different',
        },
        {
            picture: "pictures/4_150_different.jpg",
            number: 4,
            expected: "different",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different',
        },

        {
            picture: "pictures/5_50_same.jpg",
            number: 5,
            expected: "same",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different', 
        },
        {
            picture: "pictures/5_50_different.jpg",
            number: 5,
            expected: "different",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different',
        },
        {
            picture: "pictures/5_150_same.jpg",
            number: 5,
            expected: "same",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different',
        },
        {
            picture: "pictures/5_150_different.jpg",
            number: 5,
            expected: "different",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different', 
        },
        {
            picture: "pictures/6_50_same.jpg",
            number: 6,
            expected: "same",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different',
        },
        {
            picture: "pictures/6_50_different.jpg",
            number: 6,
            expected: "different",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different', 
        },
        {
            picture: "pictures/6_150_same.jpg",
            number: 6,
            expected: "same",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different', 
        },
        {
            picture: "pictures/6_150_different.jpg",
            number: 6,
            expected: "different",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different', 
        },

        {
            picture: "pictures/7_50_same.jpg",
            number: 7,
            expected: "same",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different', 
        },
        {
            picture: "pictures/7_50_different.jpg",
            number: 7,
            expected: "different",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different',
        },
        {
            picture: "pictures/7_150_same.jpg",
            number: 7,
            expected: "same",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different', 
        },
        {
            picture: "pictures/7_150_different.jpg",
            number: 7,
            expected: "different",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different', 
        },

        {
            picture: "pictures/8_50_same.jpg",
            number: 8,
            expected: "same",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different', 
        },
        {
            picture: "pictures/8_50_different.jpg",
            number: 8,
            expected: "different",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different',
        },
        {
            picture: "pictures/8_150_same.jpg",
            number: 8,
            expected: "same",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different', 
        },
        {
            picture: "pictures/8_150_different.jpg",
            number: 8,
            expected: "different",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different', 
        },

        {
            picture: "pictures/9_50_same.jpg",
            number: 9,
            expected: "same",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different', 
        },
        {
            picture: "pictures/9_50_different.jpg",
            number: 9,
            expected: "different",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different',
        },
        {
            picture: "pictures/9_150_same.jpg",
            number: 9,
            expected: "same",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different',
        },
        {
            picture: "pictures/9_150_different.jpg",
            number: 9,
            expected: "different",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different', 
        },
        {
            picture: "pictures/10_50_same.jpg",
            number: 10,
            expected: "same",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different',
        },
        {
            picture: "pictures/10_50_different.jpg",
            number: 10,
            expected: "different",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different',
        },
        {
            picture: "pictures/10_150_same.jpg",
            number: 10,
            expected: "same",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different',
        },
        {
            picture: "pictures/10_150_different.jpg",
            number: 10,
            expected: "different",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different', 
        },
        {
            picture: "pictures/11_50_same.jpg",
            number: 11,
            expected: "same",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different',
        },
        {
            picture: "pictures/11_50_different.jpg",
            number: 11,
            expected: "different",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different',
        },
        {
            picture: "pictures/11_150_same.jpg",
            number: 11,
            expected: "same",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different',
        },
        {
            picture: "pictures/11_150_different.jpg",
            number: 11,
            expected: "different",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different',
        },
        {
            picture: "pictures/12_50_same.jpg",
            number: 12,
            expected: "same",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different',
        },
        {
            picture: "pictures/12_50_different.jpg",
            number: 12,
            expected: "different",
            rotation: 50,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different',
        },
        {
            picture: "pictures/12_150_same.jpg",
            number: 12,
            expected: "same",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different',
        },
        {
            picture: "pictures/12_150_different.jpg",
            number: 12,
            expected: "different",
            rotation: 150,
			key1: 'f',
			key2: 'j',
			j: 'same',
			f: 'different',
        },
    ],
};